name: eclair
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - pip:
      - numpy
      - pandas
      - matplotlib
      - notebook
      - scikit-learn
      # Add the index URL as its own list item
      - --index-url https://download.pytorch.org/whl/cpu
      # List each package on its own line
      - torch
      - torchvision