name: eclair
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pytorch
  - torchvision
  - pip
  - pip:
      - numpy
      - pandas
      - matplotlib
      - notebook
      - scikit-learn